// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_app_api.Data;

#nullable disable

namespace quiz_app_api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240403192033_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quiz_app_api.Data.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTime")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"magnezu\",\"witaminy B\",\"\\u017Celaza\",\"witaminy D\"]",
                            Text = "Anemię powoduje niedobór:"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"w Sudetach\",\"w Tatrach\",\"w Bieszczadach\",\"w G\\u00F3rach Sto\\u0142owych\"]",
                            Text = "W których górach znajduje się Jezioro Solińskie?"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Stefan \\u017Beromski\",\"Adam Mickiewicz\",\"W\\u0142adys\\u0142aw Reymont\",\"Henryk Sienkiewicz\"]",
                            Text = "Kto jest autorem \"Syzyfowych prac\"?"
                        },
                        new
                        {
                            Id = 4,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"Lublinie\",\"Warszawie\",\"Wroc\\u0142awiu\",\"Poznaniu\"]",
                            Text = "Uniwersytet im. Adama Mickiewicza mieści się w:"
                        },
                        new
                        {
                            Id = 5,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"euro\",\"forint\",\"szyling\",\"marka austriacka\"]",
                            Text = "Jaka waluta obowiązuje w Austrii?"
                        },
                        new
                        {
                            Id = 6,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"Ocean Arktyczny\",\"Ocean Atlantycki\",\"Ocean Indyjski\",\"Ocean Spokojny\"]",
                            Text = "Który ocean jest największy?"
                        },
                        new
                        {
                            Id = 7,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Jowisz \",\"Mars\",\"Pluton\",\"Wenus\"]",
                            Text = "„Czerwoną planetą” nazywamy …"
                        },
                        new
                        {
                            Id = 8,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"fosfor\",\"\\u017Celazo\",\"srebro\",\"fluor\"]",
                            Text = "Który pierwiastek chemiczny ma symbol FE?"
                        },
                        new
                        {
                            Id = 9,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"Jan Sebastian Bach\",\"Franz Schubert\",\"Wolfgang Amadeusz Mozart\",\"Ludwig van Beethoven\"]",
                            Text = "Kto jest autorem muzyki wykorzystywanej w hymnie Unii Europejskiej?"
                        },
                        new
                        {
                            Id = 10,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"100 000 gr.\",\"1 000 000 gr.\",\"1000 gr.\",\"10 000 gr.\"]",
                            Text = "Jedna złotówka to 100 groszy, a sto złotych to...?"
                        },
                        new
                        {
                            Id = 11,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"1791 r.\",\"1830 r .\",\"1795 r.\",\"1745 r.\"]",
                            Text = "W którym roku uchwalono Konstytucję 3 Maja?"
                        },
                        new
                        {
                            Id = 12,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"amper\",\"wat\",\"om\",\"wolt\"]",
                            Text = "Co jest jednostką natężenia prądu elektrycznego?"
                        },
                        new
                        {
                            Id = 13,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"neutrofile\",\"leukocyty\",\"erytrocyty\",\"trombocyty\"]",
                            Text = "Białe krwinki to...?"
                        },
                        new
                        {
                            Id = 14,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Miko\\u0142aj Rej\",\"Juliusz S\\u0142owacki\",\"Jan Zamoyski\",\"Jan Kochanowski\"]",
                            Text = "Kto wypowiedział słynne słowa: ,,Polacy nie gęsi, iż swój język mają”?"
                        },
                        new
                        {
                            Id = 15,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Przyroda jest najwa\\u017Cniejsza\",\"B\\u00F3g jest w centrum\",\"Teologia jest najwa\\u017Cniejsza\",\"Cz\\u0142owiek jest w centrum\"]",
                            Text = "Teocentryzm to pogląd , który mówi, że:"
                        },
                        new
                        {
                            Id = 16,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"\\u015Awi\\u0119toszek\",\"Wiele ha\\u0142asu o nic\",\"Romeo i Julia\",\"Makbet\"]",
                            Text = "Którego z utworów nie napisał William Szekspir?"
                        },
                        new
                        {
                            Id = 17,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Hiperbola\",\"Anafora\",\"Epifora\",\"Oksymoron\"]",
                            Text = "Jak nazywa się środek stylistyczny, który polega na powtórzeniu tego samego wyrazu na początku sąsiadujących ze sobą wersetów?"
                        },
                        new
                        {
                            Id = 18,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"To miesi\\u0105c pogodowych niespodzianek\",\"Jest bardzo ciep\\u0142o\",\"Jest bardzo mokro\",\"Jest bardzo zimno\"]",
                            Text = "Co oznacza przysłowie: W marcu jak w garncu?"
                        },
                        new
                        {
                            Id = 19,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"W teatrze\",\"W bibliotece\",\"W operze\",\"W kawiarni\"]",
                            Text = "Gdzie Stanisław Wokulski zobaczył pannę Izabelę Łęcką po raz pierwszy?"
                        },
                        new
                        {
                            Id = 20,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Ferdydurke\",\"Szewcy\",\"Tango\",\"Granica\"]",
                            Text = "Termin ,,upupić kogoś” pochodzi z książki pt.?"
                        },
                        new
                        {
                            Id = 21,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"Henryka Sienkiewicza\",\"Stefana \\u017Beromskiego\",\"Boles\\u0142awa Prusa\",\"Zofii Na\\u0142kowskiej\"]",
                            Text = "Aleksander Głowacki to pseudonim artystyczny?:"
                        },
                        new
                        {
                            Id = 22,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"Dziady\",\"Sen nocy letniej\",\"Konrad Wallenrod\",\"Kordian\"]",
                            Text = "Który z poniższych utworów nie jest dramatem?"
                        },
                        new
                        {
                            Id = 23,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"Pozytywizm\",\"XX-lecie mi\\u0119dzywojenne\",\"Romantyzm\",\"M\\u0142oda Polska\"]",
                            Text = "Jak nazywa się epoka literacka, która trwała od 1890 do 1918 roku?"
                        },
                        new
                        {
                            Id = 24,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"z 18\",\"z 12\",\"z 14\",\"z 16\"]",
                            Text = "Z ilu krajów związkowych (landów)składa się Republika Federalna Niemiec?"
                        },
                        new
                        {
                            Id = 25,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"witaminy D\",\"witaminy K\",\"witaminy C\",\"witaminy A\"]",
                            Text = "Niedobór której witaminy powoduje szkorbut, obniża odporność organizmu i osłabia naczynia krwionośne?"
                        },
                        new
                        {
                            Id = 26,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"\\u015Blinianki\",\"dwunastnica\",\"trzustka\",\"grasica\"]",
                            Text = "Częścią układu pokarmowego człowieka nie jest:"
                        },
                        new
                        {
                            Id = 27,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"diploidalno\\u015B\\u0107\",\"dwupienno\\u015B\\u0107\",\"jednopienno\\u015B\\u0107\",\"monofagia\"]",
                            Text = "Występowanie na tej samej roślinie męskich i żeńskich narządów rozrodczych to:"
                        },
                        new
                        {
                            Id = 28,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"nietoperzach\",\"glonach\",\"porostach\",\"grzybach\"]",
                            Text = "Mykologia to nauka o:"
                        },
                        new
                        {
                            Id = 29,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"glikogen\",\"chityna\",\"celuloza\",\"kolagen\"]",
                            Text = "Cukier złożony występujący powszechnie w roślinach to"
                        },
                        new
                        {
                            Id = 30,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"woda i w\\u0119glowodany\",\"tlen i woda\",\"dwutlenek w\\u0119gla i woda\",\"tlen i w\\u0119glowodany\"]",
                            Text = "Co powstaje w wyniku fotosyntezy?"
                        },
                        new
                        {
                            Id = 31,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"ryby, gady i ptaki\",\"ssaki i ptaki\",\"wszystkie kr\\u0119gowce\",\"tylko ssaki\"]",
                            Text = "Które zwierzęta są stałocieplne?"
                        },
                        new
                        {
                            Id = 32,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"bakterie\",\"pierwotniaki\",\"wirusy\",\"paso\\u017Cyty\"]",
                            Text = "Różyczka to choroba zakaźna wywoływana przez:"
                        },
                        new
                        {
                            Id = 33,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"gru\\u017Alic\\u0119\",\"wszystkie wymienione\",\"osp\\u0119 wietrzn\\u0105\",\"w\\u015Bcieklizn\\u0119\"]",
                            Text = "Do chorób wywoływanych przez bakterie zaliczamy:"
                        },
                        new
                        {
                            Id = 34,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"gruczo\\u0142 uk\\u0142adu hormonalnego\",\"doros\\u0142a posta\\u0107 owada\",\"samozapylanie u ro\\u015Blin okrytonasiennych\",\"inaczej kora wzrokowa - cz\\u0119\\u015B\\u0107 m\\u00F3zgu odpowiedzialna za widzenie\"]",
                            Text = "Co to jest imago?"
                        },
                        new
                        {
                            Id = 35,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"adaptacji oka do widzenia przy zmiennej ilo\\u015Bci \\u015Bwiat\\u0142a\",\"neutralizowaniu wirus\\u00F3w i bakterii chorobotw\\u00F3rczych przez uk\\u0142ad odporno\\u015Bciowy organizmu\",\"podziale j\\u0105dra kom\\u00F3rkowego\",\"kopiowanie materia\\u0142u genetycznego\"]",
                            Text = "Mitoza polega na:"
                        },
                        new
                        {
                            Id = 36,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"sta\\u0142y\",\"plazma\",\"gazowy\",\"ciek\\u0142y\"]",
                            Text = "Jaki stan skupienia materii przeważa we Wszechświecie?"
                        },
                        new
                        {
                            Id = 37,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"4\",\"5\",\"2\",\"3\"]",
                            Text = "Którą planetą w kolejności od Słońca jesteśmy?"
                        },
                        new
                        {
                            Id = 38,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Neptun\",\"Saturn\",\"Jowisz\",\"Mars\"]",
                            Text = "Która planeta ma wokół siebie charakterystyczne pierścienie?"
                        },
                        new
                        {
                            Id = 39,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"Si\\u0142a od\\u015Brodkowa\",\"Si\\u0142a oporu\",\"Si\\u0142a ci\\u0119\\u017Cko\\u015Bci\",\"Si\\u0142a tarcia\"]",
                            Text = "Jaka siła powoduje ruch samochodu na rondzie?"
                        },
                        new
                        {
                            Id = 40,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Podczas ci\\u0105gni\\u0119cia sanek\",\"Podczas przenoszenia krzes\\u0142a z pokoju do kuchni\",\"Podczas hamowania\",\"Podczas podnoszenia ci\\u0119\\u017Car\\u00F3w\"]",
                            Text = "W którym przypadku nie wykonujemy pracy w sensie fizycznym?"
                        },
                        new
                        {
                            Id = 41,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Konfuzja\",\"Dyfuzja\",\"Konkluzja\",\"Parowanie\"]",
                            Text = "Jakie zjawisko odpowiada za rozchodzenie się zapachu po mieszkaniu?"
                        },
                        new
                        {
                            Id = 42,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"czyste \\u017Celazo\",\"tylko tlenki \\u017Celaza\",\"tlenki i wodorotlenki \\u017Celaza\",\"tylko wodorotlenki \\u017Celaza\"]",
                            Text = "Głównymi składnikami rdzy są:"
                        },
                        new
                        {
                            Id = 43,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Ottawa\",\"Kair\",\"Toronto\",\"Dublin\"]",
                            Text = "Które miasto jest stolicą Kanady?"
                        },
                        new
                        {
                            Id = 44,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"Pa\",\"Sn\",\"Po\",\"Cu\"]",
                            Text = "Który pierwiastek odkryła Maria Skłodowska Curie?"
                        },
                        new
                        {
                            Id = 45,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"HNO3\",\"H3PO4\",\"H2SO4\",\"HCl\"]",
                            Text = "Jaki kwas mamy w żołądku?"
                        },
                        new
                        {
                            Id = 46,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Finlandia\",\"Hiszpania\",\"Szwecja\",\"Dania\"]",
                            Text = "Który kraj nie jest monarchią?"
                        },
                        new
                        {
                            Id = 47,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Nil\",\"Missisipi\",\"Jangcy\",\"Amazonka\"]",
                            Text = "Która z tych rzek jest najdłuższa na świecie?"
                        },
                        new
                        {
                            Id = 48,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Ameryka P\\u00F3\\u0142nocna\",\"Azja\",\"Afryka\",\"Australia z Oceani\\u0105\"]",
                            Text = "Który kontynent jest największy?"
                        },
                        new
                        {
                            Id = 49,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Sekwana\",\"Tag\",\"Tamiza\",\"Loara\"]",
                            Text = "Nad którą rzeką leży Paryż?"
                        },
                        new
                        {
                            Id = 50,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Finlandia\",\"Szwajcaria\",\"Austria\",\"Malta\"]",
                            Text = "Który kraj nie należy do Unii Europejskiej?"
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.SystemStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemStatusEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 4, 3, 19, 20, 33, 83, DateTimeKind.Utc).AddTicks(6608)
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChosenOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswerEntities");
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 1,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "admin.admin",
                            Name = "admin",
                            Password = "0",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Surname = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 0,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "kamil.zdun",
                            Name = "Kamil",
                            Password = "111",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Surname = "Zdun"
                        },
                        new
                        {
                            Id = 3,
                            AccountType = 0,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "michał.zdun",
                            Name = "Michał",
                            Password = "222",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Surname = "Zdunowski"
                        },
                        new
                        {
                            Id = 4,
                            AccountType = 0,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "wojtek.zduński",
                            Name = "Wojtek",
                            Password = "333",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Surname = "Zduński"
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserAnswerEntity", b =>
                {
                    b.HasOne("quiz_app_api.Data.Entities.QuestionEntity", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quiz_app_api.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
