// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_app_api.Data;

#nullable disable

namespace quiz_app_api.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240317182312_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quiz_app_api.Data.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTime")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTime = 60,
                            CorrectAnswer = 2,
                            Options = "[\"1945\",\"1918\",\"1939\",\"1980\"]",
                            Text = "W którym roku wybuchła II Wojna Światowa?"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTime = 30,
                            CorrectAnswer = 0,
                            Options = "[\"30\",\"5\",\"10\",\"27\"]",
                            Text = "Ile lat żyją bobry"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTime = 10,
                            CorrectAnswer = 3,
                            Options = "[\"1939\",\"2006\",\"1989\",\"Nie by\\u0142o \\u017Cadnej masakry\"]",
                            Text = "W którym roku doszło do masakry na Placu Niebiańskiego Spokoju?"
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.SystemStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemStatusEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 3, 17, 18, 23, 12, 158, DateTimeKind.Utc).AddTicks(1049)
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChosenOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswerEntities");
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 1,
                            Login = "admin.admin",
                            Name = "admin",
                            Password = "0",
                            Status = 0,
                            Surname = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 0,
                            Login = "kamil.zdun",
                            Name = "Kamil",
                            Password = "111",
                            Status = 0,
                            Surname = "Zdun"
                        },
                        new
                        {
                            Id = 3,
                            AccountType = 0,
                            Login = "michał.zdun",
                            Name = "Michał",
                            Password = "222",
                            Status = 0,
                            Surname = "Zdunowski"
                        },
                        new
                        {
                            Id = 4,
                            AccountType = 0,
                            Login = "wojtek.zduński",
                            Name = "Wojtek",
                            Password = "333",
                            Status = 0,
                            Surname = "Zduński"
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserAnswerEntity", b =>
                {
                    b.HasOne("quiz_app_api.Data.Entities.QuestionEntity", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quiz_app_api.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
