// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quiz_app_api.Data;

#nullable disable

namespace quiz_app_api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("quiz_app_api.Data.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTime")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswer")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"przesz\\u0142ym z\\u0142o\\u017Conym\",\"przysz\\u0142ym z\\u0142o\\u017Conym\",\"przesz\\u0142ym prostym\",\"przesz\\u0142ym pomocniczym\"]",
                            Text = "Czas Perfekt jest czasem:"
                        },
                        new
                        {
                            Id = 2,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"przed podmiotem\",\"na drugim miejscu\",\"po czasowniku sein/haben\",\"na ostatnim miejscu\"]",
                            Text = "Czasownik pomocniczy występuje:"
                        },
                        new
                        {
                            Id = 3,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"sein i haben\",\"tylko sein\",\"tylko haben\",\"machen\"]",
                            Text = "Czasownikiem pomocniczym jest:"
                        },
                        new
                        {
                            Id = 4,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"Dativ (komu? czemu?)\",\"Genitiv (kogo? czego? czyj?)\",\"Akkusativ (kogo? co?)\",\"Nominativ (kto? co?)\"]",
                            Text = "Jaki przypadek zawsze wymaga haben jako czasownika pomocniczego?"
                        },
                        new
                        {
                            Id = 5,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"czasownik bez -en \\u002B t\",\"ge \\u002B czasownik bez -en\",\"ge \\u002B czasownik bez -en \\u002B t\",\"ge \\u002B czasownik\"]",
                            Text = "W jaki sposób tworzymy regularne czasowniki Partizip II?"
                        },
                        new
                        {
                            Id = 6,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"kiedy czasownik okre\\u015Bla ruch\",\"po czasownikach sein, bleiben i werden\",\"kiedy czasownik jest zwrotny\",\"kiedy nast\\u0119puje zmiana stanu\"]",
                            Text = "Kiedy NIE dajemy sein?"
                        },
                        new
                        {
                            Id = 7,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"sich erholen\",\"fliegen\",\"aufwachen\",\"gehen\"]",
                            Text = "Wskaż czasownik łączący się z haben"
                        },
                        new
                        {
                            Id = 8,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"denken\",\"sein\",\"machen\",\"kochen\"]",
                            Text = "Wskaż czasownik łączący się z sein"
                        },
                        new
                        {
                            Id = 9,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Haben Sie einen Termin beim Doktor Jacha\\u015B vereinbart?\",\"Hast du in Polen gewandert?\",\"Hast du zu Hause geblieben?\",\"Ich bin viel geschlafen\"]",
                            Text = "Wskaż poprawne zdanie"
                        },
                        new
                        {
                            Id = 10,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"Bist du diese Leute schon getroffen?\",\"Ich habe gestern viele Kekse gebacken\",\"Was bist du am Wochenende gemacht?\",\"Ich bin meinem Vater zum Bahnhof gefahren\"]",
                            Text = "Wskaż poprawne zdanie"
                        },
                        new
                        {
                            Id = 11,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"Du hast am Morgen viel galaufen\",\"Ich habe in der Schule gegangen\",\"Sie ist ihre Hausaufgaben gemacht\",\"Ich habe meinem Bruder zur Schule gefahren\"]",
                            Text = "Wskaż poprawne zdanie"
                        },
                        new
                        {
                            Id = 12,
                            AvailableTime = 25,
                            CorrectAnswer = 0,
                            Options = "[\"Ich bin vor drei Monaten nach Italien geflogen\",\"Ihr habt ins Kino gefahren\",\"Sie sind drei Stunden gearbeitet\",\"Wir sind uns erholt\"]",
                            Text = "Wskaż poprawne zdanie"
                        },
                        new
                        {
                            Id = 13,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"gemachen\",\"machen\",\"gemach\",\"gemacht\"]",
                            Text = "Wybierz właściwą formę Partizip II czasownika machen"
                        },
                        new
                        {
                            Id = 14,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"gearbeit\",\"gearbeitet\",\"gearbeitt\",\"gearbeiten\"]",
                            Text = "Wybierz właściwą formę Partizip II czasownika arbeiten"
                        },
                        new
                        {
                            Id = 15,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"geaufwacht\",\"aufgewachen\",\"aufgewacht\",\"geaufwachen\"]",
                            Text = "Wybierz właściwą formę Partizip II czasownika aufwachen"
                        },
                        new
                        {
                            Id = 16,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"geverkaufen\",\"vergekauft\",\"verkauft\",\"verkaufen\"]",
                            Text = "Wybierz właściwą formę Partizip II czasownika verkaufen"
                        },
                        new
                        {
                            Id = 17,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"hat getelefoniert\",\"hat telefoniert\",\"ist telefonieren\",\"ist telefoniert\"]",
                            Text = "Wybierz właściwy czasownik pomocniczy i formę Partizip II czasownika telefonieren"
                        },
                        new
                        {
                            Id = 18,
                            AvailableTime = 25,
                            CorrectAnswer = 1,
                            Options = "[\"ist gegehen\",\"ist gegangen\",\"hat gegeht\",\"hat gegehen\"]",
                            Text = "Wybierz właściwy czasownik pomocniczy i formę Partizip II czasownika gehen"
                        },
                        new
                        {
                            Id = 19,
                            AvailableTime = 25,
                            CorrectAnswer = 2,
                            Options = "[\"hat geaufstehen\",\"ist geaufstehen\",\"ist aufgestanden\",\"hat aufgestanden\"]",
                            Text = "Wybierz właściwy czasownik pomocniczy i formę Partizip II czasownika aufstehen"
                        },
                        new
                        {
                            Id = 20,
                            AvailableTime = 25,
                            CorrectAnswer = 3,
                            Options = "[\"hat eingeschlaft\",\"ist geeinschlafen\",\"hat geeinschlafen\",\"ist eingeschlafen\"]",
                            Text = "Wybierz właściwy czasownik pomocniczy i formę Partizip II czasownika einschlafen"
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.SystemStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemStatusEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableTime = 45,
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            UpdatedAt = new DateTime(2024, 4, 14, 19, 57, 0, 449, DateTimeKind.Utc).AddTicks(2502)
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChosenOption")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswerEntities");
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 1,
                            Class = "3TP",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "admin.admin",
                            Name = "admin",
                            Password = "0",
                            Status = 0,
                            Surname = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 0,
                            Class = "17",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "seumas.baxill",
                            Name = "Seumas",
                            Password = "967",
                            Status = 0,
                            Surname = "Baxill"
                        },
                        new
                        {
                            Id = 3,
                            AccountType = 0,
                            Class = "66",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "mack.waplinton",
                            Name = "Mack",
                            Password = "714",
                            Status = 0,
                            Surname = "Waplinton"
                        },
                        new
                        {
                            Id = 4,
                            AccountType = 0,
                            Class = "46",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "janetta.mcgraith",
                            Name = "Janetta",
                            Password = "411",
                            Status = 0,
                            Surname = "McGraith"
                        },
                        new
                        {
                            Id = 5,
                            AccountType = 0,
                            Class = "41",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "martita.bovey",
                            Name = "Martita",
                            Password = "222",
                            Status = 0,
                            Surname = "Bovey"
                        },
                        new
                        {
                            Id = 6,
                            AccountType = 0,
                            Class = "51",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "persis.elias",
                            Name = "Persis",
                            Password = "769",
                            Status = 0,
                            Surname = "Elias"
                        },
                        new
                        {
                            Id = 7,
                            AccountType = 0,
                            Class = "66",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "carine.golightly",
                            Name = "Carine",
                            Password = "782",
                            Status = 0,
                            Surname = "Golightly"
                        },
                        new
                        {
                            Id = 8,
                            AccountType = 0,
                            Class = "30",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ann-marie.josipovitz",
                            Name = "Ann-marie",
                            Password = "138",
                            Status = 0,
                            Surname = "Josipovitz"
                        },
                        new
                        {
                            Id = 9,
                            AccountType = 0,
                            Class = "18",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "liane.glendinning",
                            Name = "Liane",
                            Password = "864",
                            Status = 0,
                            Surname = "Glendinning"
                        },
                        new
                        {
                            Id = 10,
                            AccountType = 0,
                            Class = "56",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "garland.kindell",
                            Name = "Garland",
                            Password = "628",
                            Status = 0,
                            Surname = "Kindell"
                        },
                        new
                        {
                            Id = 11,
                            AccountType = 0,
                            Class = "86",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "cosetta.lassey",
                            Name = "Cosetta",
                            Password = "934",
                            Status = 0,
                            Surname = "Lassey"
                        },
                        new
                        {
                            Id = 12,
                            AccountType = 0,
                            Class = "28",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "thomasine.quelch",
                            Name = "Thomasine",
                            Password = "813",
                            Status = 0,
                            Surname = "Quelch"
                        },
                        new
                        {
                            Id = 13,
                            AccountType = 0,
                            Class = "17",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "maximilian.pidler",
                            Name = "Maximilian",
                            Password = "622",
                            Status = 0,
                            Surname = "Pidler"
                        },
                        new
                        {
                            Id = 14,
                            AccountType = 0,
                            Class = "70",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "leonard.letch",
                            Name = "Leonard",
                            Password = "133",
                            Status = 0,
                            Surname = "Letch"
                        },
                        new
                        {
                            Id = 15,
                            AccountType = 0,
                            Class = "15",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "tiena.matteini",
                            Name = "Tiena",
                            Password = "332",
                            Status = 0,
                            Surname = "Matteini"
                        },
                        new
                        {
                            Id = 16,
                            AccountType = 0,
                            Class = "71",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "krystal.seman",
                            Name = "Krystal",
                            Password = "582",
                            Status = 0,
                            Surname = "Seman"
                        },
                        new
                        {
                            Id = 17,
                            AccountType = 0,
                            Class = "42",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "marcela.peperell",
                            Name = "Marcela",
                            Password = "823",
                            Status = 0,
                            Surname = "Peperell"
                        },
                        new
                        {
                            Id = 18,
                            AccountType = 0,
                            Class = "72",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "gerik.melarkey",
                            Name = "Gerik",
                            Password = "173",
                            Status = 0,
                            Surname = "Melarkey"
                        },
                        new
                        {
                            Id = 19,
                            AccountType = 0,
                            Class = "51",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "rose.tousy",
                            Name = "Rose",
                            Password = "831",
                            Status = 0,
                            Surname = "Tousy"
                        },
                        new
                        {
                            Id = 20,
                            AccountType = 0,
                            Class = "93",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "jordana.dalzell",
                            Name = "Jordana",
                            Password = "497",
                            Status = 0,
                            Surname = "Dalzell"
                        },
                        new
                        {
                            Id = 21,
                            AccountType = 0,
                            Class = "80",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "silvio.hanselman",
                            Name = "Silvio",
                            Password = "443",
                            Status = 0,
                            Surname = "Hanselman"
                        },
                        new
                        {
                            Id = 22,
                            AccountType = 0,
                            Class = "49",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "harriett.twittey",
                            Name = "Harriett",
                            Password = "483",
                            Status = 0,
                            Surname = "Twittey"
                        },
                        new
                        {
                            Id = 23,
                            AccountType = 0,
                            Class = "14",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "burty.jessop",
                            Name = "Burty",
                            Password = "285",
                            Status = 0,
                            Surname = "Jessop"
                        },
                        new
                        {
                            Id = 24,
                            AccountType = 0,
                            Class = "83",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "isiahi.mandrake",
                            Name = "Isiahi",
                            Password = "188",
                            Status = 0,
                            Surname = "Mandrake"
                        },
                        new
                        {
                            Id = 25,
                            AccountType = 0,
                            Class = "28",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "jammal.snare",
                            Name = "Jammal",
                            Password = "214",
                            Status = 0,
                            Surname = "Snare"
                        },
                        new
                        {
                            Id = 26,
                            AccountType = 0,
                            Class = "69",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "crawford.davoren",
                            Name = "Crawford",
                            Password = "318",
                            Status = 0,
                            Surname = "Davoren"
                        },
                        new
                        {
                            Id = 27,
                            AccountType = 0,
                            Class = "61",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "livvie.doche",
                            Name = "Livvie",
                            Password = "752",
                            Status = 0,
                            Surname = "Doche"
                        },
                        new
                        {
                            Id = 28,
                            AccountType = 0,
                            Class = "39",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "elfreda.lafee",
                            Name = "Elfreda",
                            Password = "968",
                            Status = 0,
                            Surname = "Lafee"
                        },
                        new
                        {
                            Id = 29,
                            AccountType = 0,
                            Class = "71",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "hadleigh.fishbourn",
                            Name = "Hadleigh",
                            Password = "288",
                            Status = 0,
                            Surname = "Fishbourn"
                        },
                        new
                        {
                            Id = 30,
                            AccountType = 0,
                            Class = "69",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "deanne.warboys",
                            Name = "Deanne",
                            Password = "474",
                            Status = 0,
                            Surname = "Warboys"
                        },
                        new
                        {
                            Id = 31,
                            AccountType = 0,
                            Class = "81",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ailbert.handasyde",
                            Name = "Ailbert",
                            Password = "387",
                            Status = 0,
                            Surname = "Handasyde"
                        },
                        new
                        {
                            Id = 32,
                            AccountType = 0,
                            Class = "42",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "guenna.o'hengerty",
                            Name = "Guenna",
                            Password = "576",
                            Status = 0,
                            Surname = "O'Hengerty"
                        },
                        new
                        {
                            Id = 33,
                            AccountType = 0,
                            Class = "88",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "arluene.figurski",
                            Name = "Arluene",
                            Password = "752",
                            Status = 0,
                            Surname = "Figurski"
                        },
                        new
                        {
                            Id = 34,
                            AccountType = 0,
                            Class = "76",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "wendall.guswell",
                            Name = "Wendall",
                            Password = "646",
                            Status = 0,
                            Surname = "Guswell"
                        },
                        new
                        {
                            Id = 35,
                            AccountType = 0,
                            Class = "78",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "raye.schreurs",
                            Name = "Raye",
                            Password = "973",
                            Status = 0,
                            Surname = "Schreurs"
                        },
                        new
                        {
                            Id = 36,
                            AccountType = 0,
                            Class = "65",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "zach.de filippo",
                            Name = "Zach",
                            Password = "237",
                            Status = 0,
                            Surname = "De Filippo"
                        },
                        new
                        {
                            Id = 37,
                            AccountType = 0,
                            Class = "43",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "karina.hailes",
                            Name = "Karina",
                            Password = "148",
                            Status = 0,
                            Surname = "Hailes"
                        },
                        new
                        {
                            Id = 38,
                            AccountType = 0,
                            Class = "55",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "orly.pleasaunce",
                            Name = "Orly",
                            Password = "735",
                            Status = 0,
                            Surname = "Pleasaunce"
                        },
                        new
                        {
                            Id = 39,
                            AccountType = 0,
                            Class = "82",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "peter.klain",
                            Name = "Peter",
                            Password = "377",
                            Status = 0,
                            Surname = "Klain"
                        },
                        new
                        {
                            Id = 40,
                            AccountType = 0,
                            Class = "18",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "peta.aspland",
                            Name = "Peta",
                            Password = "235",
                            Status = 0,
                            Surname = "Aspland"
                        },
                        new
                        {
                            Id = 41,
                            AccountType = 0,
                            Class = "28",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "norbie.baldree",
                            Name = "Norbie",
                            Password = "368",
                            Status = 0,
                            Surname = "Baldree"
                        },
                        new
                        {
                            Id = 42,
                            AccountType = 0,
                            Class = "47",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ethyl.kneel",
                            Name = "Ethyl",
                            Password = "982",
                            Status = 0,
                            Surname = "Kneel"
                        },
                        new
                        {
                            Id = 43,
                            AccountType = 0,
                            Class = "52",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "lissy.theml",
                            Name = "Lissy",
                            Password = "242",
                            Status = 0,
                            Surname = "Theml"
                        },
                        new
                        {
                            Id = 44,
                            AccountType = 0,
                            Class = "33",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "felipe.dinneen",
                            Name = "Felipe",
                            Password = "442",
                            Status = 0,
                            Surname = "Dinneen"
                        },
                        new
                        {
                            Id = 45,
                            AccountType = 0,
                            Class = "85",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "abra.coad",
                            Name = "Abra",
                            Password = "826",
                            Status = 0,
                            Surname = "Coad"
                        },
                        new
                        {
                            Id = 46,
                            AccountType = 0,
                            Class = "12",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "dill.jales",
                            Name = "Dill",
                            Password = "627",
                            Status = 0,
                            Surname = "Jales"
                        },
                        new
                        {
                            Id = 47,
                            AccountType = 0,
                            Class = "90",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "jackelyn.broadwell",
                            Name = "Jackelyn",
                            Password = "989",
                            Status = 0,
                            Surname = "Broadwell"
                        },
                        new
                        {
                            Id = 48,
                            AccountType = 0,
                            Class = "90",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ines.rome",
                            Name = "Ines",
                            Password = "455",
                            Status = 0,
                            Surname = "Rome"
                        },
                        new
                        {
                            Id = 49,
                            AccountType = 0,
                            Class = "54",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "laryssa.maughan",
                            Name = "Laryssa",
                            Password = "136",
                            Status = 0,
                            Surname = "Maughan"
                        },
                        new
                        {
                            Id = 50,
                            AccountType = 0,
                            Class = "95",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "marcela.loweth",
                            Name = "Marcela",
                            Password = "271",
                            Status = 0,
                            Surname = "Loweth"
                        },
                        new
                        {
                            Id = 51,
                            AccountType = 0,
                            Class = "80",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "abraham.errichelli",
                            Name = "Abraham",
                            Password = "945",
                            Status = 0,
                            Surname = "Errichelli"
                        },
                        new
                        {
                            Id = 52,
                            AccountType = 0,
                            Class = "11",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "cristionna.leyland",
                            Name = "Cristionna",
                            Password = "628",
                            Status = 0,
                            Surname = "Leyland"
                        },
                        new
                        {
                            Id = 53,
                            AccountType = 0,
                            Class = "100",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "humberto.routham",
                            Name = "Humberto",
                            Password = "273",
                            Status = 0,
                            Surname = "Routham"
                        },
                        new
                        {
                            Id = 54,
                            AccountType = 0,
                            Class = "76",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "joice.lipp",
                            Name = "Joice",
                            Password = "582",
                            Status = 0,
                            Surname = "Lipp"
                        },
                        new
                        {
                            Id = 55,
                            AccountType = 0,
                            Class = "6",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "barbe.kennaird",
                            Name = "Barbe",
                            Password = "738",
                            Status = 0,
                            Surname = "Kennaird"
                        },
                        new
                        {
                            Id = 56,
                            AccountType = 0,
                            Class = "1",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ignaz.erett",
                            Name = "Ignaz",
                            Password = "278",
                            Status = 0,
                            Surname = "Erett"
                        },
                        new
                        {
                            Id = 57,
                            AccountType = 0,
                            Class = "67",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "patience.tunmore",
                            Name = "Patience",
                            Password = "594",
                            Status = 0,
                            Surname = "Tunmore"
                        },
                        new
                        {
                            Id = 58,
                            AccountType = 0,
                            Class = "79",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "costa.murrigan",
                            Name = "Costa",
                            Password = "822",
                            Status = 0,
                            Surname = "Murrigan"
                        },
                        new
                        {
                            Id = 59,
                            AccountType = 0,
                            Class = "66",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "pedro.stetson",
                            Name = "Pedro",
                            Password = "814",
                            Status = 0,
                            Surname = "Stetson"
                        },
                        new
                        {
                            Id = 60,
                            AccountType = 0,
                            Class = "96",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "palm.cranmore",
                            Name = "Palm",
                            Password = "625",
                            Status = 0,
                            Surname = "Cranmore"
                        },
                        new
                        {
                            Id = 61,
                            AccountType = 0,
                            Class = "61",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "emilio.fergie",
                            Name = "Emilio",
                            Password = "922",
                            Status = 0,
                            Surname = "Fergie"
                        },
                        new
                        {
                            Id = 62,
                            AccountType = 0,
                            Class = "50",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ericka.o'heyne",
                            Name = "Ericka",
                            Password = "953",
                            Status = 0,
                            Surname = "O'Heyne"
                        },
                        new
                        {
                            Id = 63,
                            AccountType = 0,
                            Class = "85",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "hazel.mcsarry",
                            Name = "Hazel",
                            Password = "755",
                            Status = 0,
                            Surname = "Mcsarry"
                        },
                        new
                        {
                            Id = 64,
                            AccountType = 0,
                            Class = "67",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "mirabella.le fleming",
                            Name = "Mirabella",
                            Password = "676",
                            Status = 0,
                            Surname = "Le Fleming"
                        },
                        new
                        {
                            Id = 65,
                            AccountType = 0,
                            Class = "39",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ilyse.kanter",
                            Name = "Ilyse",
                            Password = "986",
                            Status = 0,
                            Surname = "Kanter"
                        },
                        new
                        {
                            Id = 66,
                            AccountType = 0,
                            Class = "71",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "mychal.guidone",
                            Name = "Mychal",
                            Password = "296",
                            Status = 0,
                            Surname = "Guidone"
                        },
                        new
                        {
                            Id = 67,
                            AccountType = 0,
                            Class = "22",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "rosie.tuckerman",
                            Name = "Rosie",
                            Password = "969",
                            Status = 0,
                            Surname = "Tuckerman"
                        },
                        new
                        {
                            Id = 68,
                            AccountType = 0,
                            Class = "56",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "erroll.camlin",
                            Name = "Erroll",
                            Password = "666",
                            Status = 0,
                            Surname = "Camlin"
                        },
                        new
                        {
                            Id = 69,
                            AccountType = 0,
                            Class = "35",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "chad.ruprecht",
                            Name = "Chad",
                            Password = "667",
                            Status = 0,
                            Surname = "Ruprecht"
                        },
                        new
                        {
                            Id = 70,
                            AccountType = 0,
                            Class = "4",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "taber.zincke",
                            Name = "Taber",
                            Password = "964",
                            Status = 0,
                            Surname = "Zincke"
                        },
                        new
                        {
                            Id = 71,
                            AccountType = 0,
                            Class = "65",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "katheryn.d'escoffier",
                            Name = "Katheryn",
                            Password = "348",
                            Status = 0,
                            Surname = "d'Escoffier"
                        },
                        new
                        {
                            Id = 72,
                            AccountType = 0,
                            Class = "42",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "genovera.augustin",
                            Name = "Genovera",
                            Password = "285",
                            Status = 0,
                            Surname = "Augustin"
                        },
                        new
                        {
                            Id = 73,
                            AccountType = 0,
                            Class = "74",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "benjy.cowlard",
                            Name = "Benjy",
                            Password = "345",
                            Status = 0,
                            Surname = "Cowlard"
                        },
                        new
                        {
                            Id = 74,
                            AccountType = 0,
                            Class = "76",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ralina.garraway",
                            Name = "Ralina",
                            Password = "329",
                            Status = 0,
                            Surname = "Garraway"
                        },
                        new
                        {
                            Id = 75,
                            AccountType = 0,
                            Class = "40",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "heather.desforges",
                            Name = "Heather",
                            Password = "943",
                            Status = 0,
                            Surname = "Desforges"
                        },
                        new
                        {
                            Id = 76,
                            AccountType = 0,
                            Class = "51",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "tersina.cancott",
                            Name = "Tersina",
                            Password = "315",
                            Status = 0,
                            Surname = "Cancott"
                        },
                        new
                        {
                            Id = 77,
                            AccountType = 0,
                            Class = "6",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "loy.martinuzzi",
                            Name = "Loy",
                            Password = "644",
                            Status = 0,
                            Surname = "Martinuzzi"
                        },
                        new
                        {
                            Id = 78,
                            AccountType = 0,
                            Class = "36",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "dill.eames",
                            Name = "Dill",
                            Password = "664",
                            Status = 0,
                            Surname = "Eames"
                        },
                        new
                        {
                            Id = 79,
                            AccountType = 0,
                            Class = "52",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "dell.hardway",
                            Name = "Dell",
                            Password = "394",
                            Status = 0,
                            Surname = "Hardway"
                        },
                        new
                        {
                            Id = 80,
                            AccountType = 0,
                            Class = "52",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "erick.floyd",
                            Name = "Erick",
                            Password = "532",
                            Status = 0,
                            Surname = "Floyd"
                        },
                        new
                        {
                            Id = 81,
                            AccountType = 0,
                            Class = "53",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "helenelizabeth.scoffins",
                            Name = "Helenelizabeth",
                            Password = "558",
                            Status = 0,
                            Surname = "Scoffins"
                        },
                        new
                        {
                            Id = 82,
                            AccountType = 0,
                            Class = "95",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "felix.pudner",
                            Name = "Felix",
                            Password = "927",
                            Status = 0,
                            Surname = "Pudner"
                        },
                        new
                        {
                            Id = 83,
                            AccountType = 0,
                            Class = "99",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "nydia.ritch",
                            Name = "Nydia",
                            Password = "977",
                            Status = 0,
                            Surname = "Ritch"
                        },
                        new
                        {
                            Id = 84,
                            AccountType = 0,
                            Class = "91",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "sheffie.bonnick",
                            Name = "Sheffie",
                            Password = "436",
                            Status = 0,
                            Surname = "Bonnick"
                        },
                        new
                        {
                            Id = 85,
                            AccountType = 0,
                            Class = "70",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "dominick.evennett",
                            Name = "Dominick",
                            Password = "721",
                            Status = 0,
                            Surname = "Evennett"
                        },
                        new
                        {
                            Id = 86,
                            AccountType = 0,
                            Class = "74",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "peirce.kembley",
                            Name = "Peirce",
                            Password = "273",
                            Status = 0,
                            Surname = "Kembley"
                        },
                        new
                        {
                            Id = 87,
                            AccountType = 0,
                            Class = "74",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "torrance.gianettini",
                            Name = "Torrance",
                            Password = "539",
                            Status = 0,
                            Surname = "Gianettini"
                        },
                        new
                        {
                            Id = 88,
                            AccountType = 0,
                            Class = "68",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "bryce.sutherden",
                            Name = "Bryce",
                            Password = "373",
                            Status = 0,
                            Surname = "Sutherden"
                        },
                        new
                        {
                            Id = 89,
                            AccountType = 0,
                            Class = "71",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "alexandra.mckeney",
                            Name = "Alexandra",
                            Password = "914",
                            Status = 0,
                            Surname = "McKeney"
                        },
                        new
                        {
                            Id = 90,
                            AccountType = 0,
                            Class = "82",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "paul.grieger",
                            Name = "Paul",
                            Password = "746",
                            Status = 0,
                            Surname = "Grieger"
                        },
                        new
                        {
                            Id = 91,
                            AccountType = 0,
                            Class = "11",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "prudi.torns",
                            Name = "Prudi",
                            Password = "689",
                            Status = 0,
                            Surname = "Torns"
                        },
                        new
                        {
                            Id = 92,
                            AccountType = 0,
                            Class = "75",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "madonna.costelow",
                            Name = "Madonna",
                            Password = "426",
                            Status = 0,
                            Surname = "Costelow"
                        },
                        new
                        {
                            Id = 93,
                            AccountType = 0,
                            Class = "96",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "brandie.luparti",
                            Name = "Brandie",
                            Password = "842",
                            Status = 0,
                            Surname = "Luparti"
                        },
                        new
                        {
                            Id = 94,
                            AccountType = 0,
                            Class = "89",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "ky.epelett",
                            Name = "Ky",
                            Password = "318",
                            Status = 0,
                            Surname = "Epelett"
                        },
                        new
                        {
                            Id = 95,
                            AccountType = 0,
                            Class = "44",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "hester.peracco",
                            Name = "Hester",
                            Password = "374",
                            Status = 0,
                            Surname = "Peracco"
                        },
                        new
                        {
                            Id = 96,
                            AccountType = 0,
                            Class = "60",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "gill.starbucke",
                            Name = "Gill",
                            Password = "196",
                            Status = 0,
                            Surname = "Starbucke"
                        },
                        new
                        {
                            Id = 97,
                            AccountType = 0,
                            Class = "23",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "jerrie.stoter",
                            Name = "Jerrie",
                            Password = "868",
                            Status = 0,
                            Surname = "Stoter"
                        },
                        new
                        {
                            Id = 98,
                            AccountType = 0,
                            Class = "13",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "urbanus.fancet",
                            Name = "Urbanus",
                            Password = "733",
                            Status = 0,
                            Surname = "Fancet"
                        },
                        new
                        {
                            Id = 99,
                            AccountType = 0,
                            Class = "74",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "michaelina.mcbeith",
                            Name = "Michaelina",
                            Password = "897",
                            Status = 0,
                            Surname = "McBeith"
                        },
                        new
                        {
                            Id = 100,
                            AccountType = 0,
                            Class = "41",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "fedora.sonier",
                            Name = "Fedora",
                            Password = "621",
                            Status = 0,
                            Surname = "Sonier"
                        },
                        new
                        {
                            Id = 101,
                            AccountType = 0,
                            Class = "61",
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "berenice.sewter",
                            Name = "Berenice",
                            Password = "797",
                            Status = 0,
                            Surname = "Sewter"
                        });
                });

            modelBuilder.Entity("quiz_app_api.Data.Entities.UserAnswerEntity", b =>
                {
                    b.HasOne("quiz_app_api.Data.Entities.QuestionEntity", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("quiz_app_api.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
